title: Tangible Interfaces
description: >-
  Senior Industrial Design Studio at Pratt Institute.
  Designing with tactile and sensory components to build
  interactive user experiences embodied in physical products.
url: https://turbek.com
baseurl: /tangible-interfaces

# Build settings
markdown: kramdown
permalink: none
theme: null

# Default layout for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      layout: default
      permalink: /blog/:year/:month/:day/:title/

# Exclude files from the build
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - setup.md
  - Gemfile
  - Gemfile.lock
